<?php include "menu.php" ?>
<link rel="stylesheet" href="styleflex.css">
<?php
echo '<div class="flexcontainer">';
    echo '<div class="bin one">';
        echo '<div class="navigation1">';
            echo '<div class="row1">';
                echo '<a href=""><b>Link 1</b></a>';
                echo '<a href=""><b>Link 2</b></a>';
                echo '<a href=""><b>Link 3</b></a>';
            echo '</div>';
        echo '</div>';
    echo '</div>';
    echo '<div class="bin two">';
        echo '<div class="navigation1">';
            echo '<div class="row2">';
                echo '<a href=""><b>Link 4</b></a>';
                echo '<a href=""><b>Link 5</b></a>';
                echo '<a href=""><b>Link 6</b></a>';
            echo '</div>';
        echo '</div>';
    echo '</div>';
    echo '<div class="bin three">';
        echo '<div class="navigation1">';
            echo '<div class="column1">';
                echo '<a href=""><b>Link 7</b></a>';
                echo '<a href=""><b>Link 8</b></a>';
                echo '<a href=""><b>Link 9</b></a>';
            echo '</div>';
        echo '</div>';
    echo '</div>';
    echo '<div class="bin four">';
        echo '<div class="navigation1">';
            echo '<div class="column2">';
                echo '<a href=""><b>Link 10</b></a>';
                echo '<a href=""><b>Link 11</b></a>';
                echo '<a href=""><b>Link 12</b></a>';
            echo '</div>';
        echo '</div>';
    echo '</div>';
     echo '<div class="bin five">';
            echo '<ul class="navigation"></ul>';
            echo '<ul class="navigation"></ul>';
        echo '</div>';
    echo '<div class="bin six">';
        echo '<ul class="navigation"></ul>';
        echo '<ul class="navigation"></ul>';
    echo '</div>';
    echo '<div class="bin seven">';
        echo '<ul class="navigation"></ul>';
        echo '<ul class="navigation"></ul>';
    echo '</div>';
    echo '<div class="bin eight">';
        echo '<ul class="navigation space"></ul>';
        echo '<ul class="navigation space"></ul>';
    echo '</div>';
    echo '<div class="bin nine">';
        echo '<ul class="navigation space"></ul>';
        echo '<ul class="navigation space"></ul>';
    echo '</div>';
        echo '<div class="bin ten">';
            echo '<ul class="navigation space"></ul>';
            echo '<ul class="navigation space"></ul>';
        echo '</div>';
        echo '<div class="bin eleven">';
            echo '<ul class="navigation space"></ul>';
            echo '<ul class="navigation space"></ul>';
        echo '</div>';
        echo '<div class="bin twelve">';
            echo '<ul class="navigation space"></ul>';
            echo '<ul class="navigation space"></ul>';
        echo '</div>';
?>
